import { Inter } from 'next/font/google'
import './globals.css'
import NavBar from '@/components/NavBar'
import Home from '@/components/Home'
import Social from '@/components/Social'
import About from '@/components/About'
import Projects from '@/components/Projects'
import Experience from '@/components/Experience'
import Contact from '@/components/Contact'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Swarnadeep',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NavBar/>
        <Home/>

        <About/>
        <Experience/>
        <Projects/>
        <Contact/>
        <Social/>
        {children}</body>
    </html>
  )
}
